# Generated by Django 4.2.2 on 2023-06-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_user', '0003_alter_sendrequest_receive_alter_sendrequest_send'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendrequest',
            old_name='send',
            new_name='sender',
        ),
    ]
