# Generated by Django 4.2.2 on 2023-06-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_user', '0004_rename_send_sendrequest_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrequest',
            name='status',
            field=models.CharField(choices=[('Follow', 'follow'), ('Following', 'following'), ('Requested', 'requested'), ('Confirm', 'confirm'), ('Delete', 'delete'), ('Accept', 'accept')], default='Follow', max_length=20, null=True),
        ),
    ]
