# Generated by Django 4.2.2 on 2023-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_user', '0007_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
