# Generated by Django 4.2.2 on 2023-07-03 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('follow_user', '0009_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
