# Generated by Django 4.2.2 on 2023-07-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_user', '0010_commentpost_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentPost',
        ),
        migrations.DeleteModel(
            name='LikePost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
