# Generated by Django 4.2.2 on 2023-07-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/profile'),
        ),
    ]
