# Generated by Django 4.2.2 on 2023-07-10 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0002_rename_user_likepost_like_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='like_by',
        ),
        migrations.AddField(
            model_name='likepost',
            name='like_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
