# Generated by Django 4.2.2 on 2023-07-10 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0003_likepost_user_remove_likepost_like_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='user',
        ),
        migrations.AddField(
            model_name='likepost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='like_by',
        ),
        migrations.AddField(
            model_name='likepost',
            name='like_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
