# Generated by Django 4.2.2 on 2023-07-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_likepost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='user',
        ),
    ]
